package com.example.outbounddemo0629.model;

public class CdrTableA {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.uuid
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.call_uuid
     *
     * @mbg.generated
     */
    private String callUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.caller_id_name
     *
     * @mbg.generated
     */
    private String callerIdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.caller_id_number
     *
     * @mbg.generated
     */
    private String callerIdNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.destination_number
     *
     * @mbg.generated
     */
    private String destinationNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.start_stamp
     *
     * @mbg.generated
     */
    private String startStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.answer_stamp
     *
     * @mbg.generated
     */
    private String answerStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.end_stamp
     *
     * @mbg.generated
     */
    private String endStamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.uduration
     *
     * @mbg.generated
     */
    private String uduration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.billsec
     *
     * @mbg.generated
     */
    private String billsec;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.hangup_cause
     *
     * @mbg.generated
     */
    private String hangupCause;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdr_table_a.success
     *
     * @mbg.generated
     */
    private String success;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.uuid
     *
     * @return the value of cdr_table_a.uuid
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.uuid
     *
     * @param uuid the value for cdr_table_a.uuid
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.call_uuid
     *
     * @return the value of cdr_table_a.call_uuid
     *
     * @mbg.generated
     */
    public String getCallUuid() {
        return callUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.call_uuid
     *
     * @param callUuid the value for cdr_table_a.call_uuid
     *
     * @mbg.generated
     */
    public void setCallUuid(String callUuid) {
        this.callUuid = callUuid == null ? null : callUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.caller_id_name
     *
     * @return the value of cdr_table_a.caller_id_name
     *
     * @mbg.generated
     */
    public String getCallerIdName() {
        return callerIdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.caller_id_name
     *
     * @param callerIdName the value for cdr_table_a.caller_id_name
     *
     * @mbg.generated
     */
    public void setCallerIdName(String callerIdName) {
        this.callerIdName = callerIdName == null ? null : callerIdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.caller_id_number
     *
     * @return the value of cdr_table_a.caller_id_number
     *
     * @mbg.generated
     */
    public String getCallerIdNumber() {
        return callerIdNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.caller_id_number
     *
     * @param callerIdNumber the value for cdr_table_a.caller_id_number
     *
     * @mbg.generated
     */
    public void setCallerIdNumber(String callerIdNumber) {
        this.callerIdNumber = callerIdNumber == null ? null : callerIdNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.destination_number
     *
     * @return the value of cdr_table_a.destination_number
     *
     * @mbg.generated
     */
    public String getDestinationNumber() {
        return destinationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.destination_number
     *
     * @param destinationNumber the value for cdr_table_a.destination_number
     *
     * @mbg.generated
     */
    public void setDestinationNumber(String destinationNumber) {
        this.destinationNumber = destinationNumber == null ? null : destinationNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.start_stamp
     *
     * @return the value of cdr_table_a.start_stamp
     *
     * @mbg.generated
     */
    public String getStartStamp() {
        return startStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.start_stamp
     *
     * @param startStamp the value for cdr_table_a.start_stamp
     *
     * @mbg.generated
     */
    public void setStartStamp(String startStamp) {
        this.startStamp = startStamp == null ? null : startStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.answer_stamp
     *
     * @return the value of cdr_table_a.answer_stamp
     *
     * @mbg.generated
     */
    public String getAnswerStamp() {
        return answerStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.answer_stamp
     *
     * @param answerStamp the value for cdr_table_a.answer_stamp
     *
     * @mbg.generated
     */
    public void setAnswerStamp(String answerStamp) {
        this.answerStamp = answerStamp == null ? null : answerStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.end_stamp
     *
     * @return the value of cdr_table_a.end_stamp
     *
     * @mbg.generated
     */
    public String getEndStamp() {
        return endStamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.end_stamp
     *
     * @param endStamp the value for cdr_table_a.end_stamp
     *
     * @mbg.generated
     */
    public void setEndStamp(String endStamp) {
        this.endStamp = endStamp == null ? null : endStamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.uduration
     *
     * @return the value of cdr_table_a.uduration
     *
     * @mbg.generated
     */
    public String getUduration() {
        return uduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.uduration
     *
     * @param uduration the value for cdr_table_a.uduration
     *
     * @mbg.generated
     */
    public void setUduration(String uduration) {
        this.uduration = uduration == null ? null : uduration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.billsec
     *
     * @return the value of cdr_table_a.billsec
     *
     * @mbg.generated
     */
    public String getBillsec() {
        return billsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.billsec
     *
     * @param billsec the value for cdr_table_a.billsec
     *
     * @mbg.generated
     */
    public void setBillsec(String billsec) {
        this.billsec = billsec == null ? null : billsec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.hangup_cause
     *
     * @return the value of cdr_table_a.hangup_cause
     *
     * @mbg.generated
     */
    public String getHangupCause() {
        return hangupCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.hangup_cause
     *
     * @param hangupCause the value for cdr_table_a.hangup_cause
     *
     * @mbg.generated
     */
    public void setHangupCause(String hangupCause) {
        this.hangupCause = hangupCause == null ? null : hangupCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.state
     *
     * @return the value of cdr_table_a.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.state
     *
     * @param state the value for cdr_table_a.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdr_table_a.success
     *
     * @return the value of cdr_table_a.success
     *
     * @mbg.generated
     */
    public String getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdr_table_a.success
     *
     * @param success the value for cdr_table_a.success
     *
     * @mbg.generated
     */
    public void setSuccess(String success) {
        this.success = success == null ? null : success.trim();
    }
}