package com.example.outbounddemo0629.mapper;

import com.example.outbounddemo0629.model.CdrTableA;
import java.util.List;

public interface CdrTableAMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdr_table_a
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdr_table_a
     *
     * @mbg.generated
     */
    int insert(CdrTableA row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdr_table_a
     *
     * @mbg.generated
     */
    CdrTableA selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdr_table_a
     *
     * @mbg.generated
     */
    List<CdrTableA> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdr_table_a
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CdrTableA row);
}